/*
  Authentication action types
*/
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'
export const AUTH_RESET = 'AUTH_RESET'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REGISTER = 'AUTH_REGISTER'

export const CREATE_PATIENT = 'CREATE_PATIENT'
export const QUERY_PATIENT_PROFILE = 'QUERY_PATIENT_PROFILE'
export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS'
export const CLEAR_CURRENT_PATIENT = 'CLEAR_CURRENT_PATIENT'
export const QUERY_PATIENT_PROFILE_SUCCESS = 'QUERY_PATIENT_PROFILE_SUCCESS'

export const UPDATE_PATIENT = 'UPDATE_PATIENT'
export const DELETE_PATIENT = 'DELETE_PATIENT'
export const FETCH_PATIENT = 'FETCH_PATIENT'