export const CREATE_VITALS_RECORD = 'CREATE_VITALS_RECORD'
export const UPDATE_VITALS_RECORD = 'UPDATE_VITALS_RECORD'
export const REMOVE_VITALS_RECORD = 'REMOVE_VITALS_RECORD'
export const FETCH_VITALS_RECORD = 'FETCH_VITALS_RECORD'
